image: gradle:8.6-jdk21-alpine

stages:
  - build
  - test
  - security-test
  - deploy

.statistics-common:
  rules:
    - changes:
        - 'StatisticsContext/*'

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

statistics-build:
  stage: build
  extends: .statistics-common
  script:
    - gradle --build-cache :StatisticsContext:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

statistics-unit-test:
  stage: test
  extends: .statistics-common
  services:
    - docker:24.0.5-dind
    - postgres:16.1-alpine
  variables:
    POSTGRES_DB: 'demo-test'
    POSTGRES_USER: 'admin'
    POSTGRES_PASSWORD: 'test'
    CI_DB_HOST_PORT: 'postgres:5432'
  script:
    - gradle :StatisticsContext:unitTest --no-daemon
  artifacts:
    when: always
    reports:
      junit: StatisticsContext/build/test-results/unitTest/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

statistics-integration-test:
  stage: test
  extends: .statistics-common
  services:
    - docker:24.0.5-dind
    - postgres:16.1-alpine
  variables:
    DOCKER_HOST: tcp://docker:2375
    POSTGRES_DB: 'demo-test'
    POSTGRES_USER: 'admin'
    POSTGRES_PASSWORD: 'test'
    CI_DB_HOST_PORT: 'postgres:5432'
  script:
    - gradle :StatisticsContext:integrationTest --no-daemon
  artifacts:
    when: always
    reports:
      junit: StatisticsContext/build/test-results/integrationTest/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle 

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

statistics-sast:
  extends: .sast
  stage: security-test

statistics-secret_detection:
  extends: .secret-detection
  stage: security-test

statistics-dependency_scanning:
  extends: .dependency-scanning
  stage: security-test

statistics-trigger-gcb:
  image: google/cloud-sdk:latest
  stage: deploy
  extends: .statistics-common
  identity: google_cloud
  script:
    - gcloud config set project $GCLOUD_PROJECT
    - gcloud builds triggers run statistics-context --region europe-west1
  