stages:
  - build
  - test
  - upload
  - deploy

workflow:
 rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

include:
  - local: '/GamePlatformContext/game-context-gitlab-ci.yml'
