stages:
  - build
  - test
  - upload
  - deploy

workflow:
 rules:
     - if: '$CI_MERGE_REQUEST_ID'
       when: never

include:
  - local: '/GamePlatformContext/game-context-gitlab-ci.yml'
