stages:
  - build
  - test
  - upload
  - deploy

workflow:
 rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

include:
  - local: '/GamePlatformContext/game-context-gitlab-ci.yml'
