stages:
  - build
  - test
  - upload
  - deploy

include:
  - local: '/GamePlatformContext/game-context-gitlab-ci.yml'
    rules: 
      - if: $CI_PIPELINE_SOURCE != "merge_request_event"
        when: always


test:
  stage: test
  script:
    - exit 0
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never