stages:
  - build
  - test
  - upload
  - deploy

workflow:
 rules:
     - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
       when: always
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
       when: never

include:
  - local: '/GamePlatformContext/game-context-gitlab-ci.yml'
