stages:
  - build
  - test
  - upload
  - deploy

workflow:
 rules:
     - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
       when: never

include:
  - local: '/GamePlatformContext/game-context-gitlab-ci.yml'
