  services:
    postgres_games_db:
      image: 'postgres:16.1-alpine'
      restart: always
      environment:
        - 'POSTGRES_DB=gameplatform'
        - 'POSTGRES_USER=game_admin'
        - 'POSTGRES_PASSWORD=game_admin_password'
      ports:
        - '5440:5432'
      networks:
        - backend
      volumes:
        - ./postgres/data:/var/lib/postgres

    app_rabbitmq:
      image: rabbitmq:3.13.7-management-alpine
      environment:
        - RABBITMQ_DEFAULT_USER=game_user
        - RABBITMQ_DEFAULT_PASS=game_user_password
      ports:
        - "5672:5672" #AMQP
        - "15672:15672" #MGMT
      networks:
        - backend
      volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq/


  networks:
    kc:
      name: kc-network
      driver: bridge
    backend:
      name: back-network
      driver: bridge

