steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest || exit 0']

- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '-t', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:$TAG_NAME',
          '--cache-from', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest',
          '-f',
          'GamePlatformContext/Dockerfile',
          '.'          
        ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME:$TAG_NAME'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'run',
        'deploy',
        '$SERVICE_NAME',
        '--image',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME:$TAG_NAME',
        '--region',
        '$LOCATION',
        '--port',
        '3000',
        '--vpc-connector',
        'my-vpc-connector',
        '--ingress',
        'internal',
        '--allow-unauthenticated'
      ]

substitutions:
  _PROJECT_ID: 'checkers-integration5' 
  _REPO_NAME: 'checkers-repo'                
  _SERVICE_NAME: 'gameplatform-service'      
  _LOCATION: 'europe-west1',
  _TAG_NAME: 'latest'                         

images: ['gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest']                 
