image: gradle:8.4.1-jdk21

stages:
  - build
  - unit-test
  - integration-test
  # - deploy-gcb test

.gameplatform-common:
  rules:
    - changes:
        - 'GamePlatformContext/*'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never


.variables:
  POSTGRES_DB: 'demo-db'
  POSTGRES_USER: 'admin'
  POSTGRES_PASSWORD: 'test'
  CI_DB_HOST_PORT: 'postgres:5432'

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  extends: .gameplatform-common
  script:
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

unit-test:
  stage: unit-test
  extends: .gameplatform-common
  services:
    - postgres:16.1-alpine
  script:
    - gradle :GamePlatformContext:unitTest --no-daemon
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

integration-test:
  stage: integration-test
  extends: .gameplatform-common
  services:
    - postgres:16.1-alpine
  script:
    - gradle :GamePlatformContext:integrationTest --no-daemon
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle